//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.CalculateAge.Client.CalculateAgeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalculateAgeService.CalculateAgeServiceSoap")]
    public interface CalculateAgeServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculateAge", ReplyAction="*")]
        int CalculateAge(System.DateTime dateOfBirth);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculateAge", ReplyAction="*")]
        System.Threading.Tasks.Task<int> CalculateAgeAsync(System.DateTime dateOfBirth);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculateAgeServiceSoapChannel : WCF.CalculateAge.Client.CalculateAgeService.CalculateAgeServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculateAgeServiceSoapClient : System.ServiceModel.ClientBase<WCF.CalculateAge.Client.CalculateAgeService.CalculateAgeServiceSoap>, WCF.CalculateAge.Client.CalculateAgeService.CalculateAgeServiceSoap {
        
        public CalculateAgeServiceSoapClient() {
        }
        
        public CalculateAgeServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculateAgeServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculateAgeServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculateAgeServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CalculateAge(System.DateTime dateOfBirth) {
            return base.Channel.CalculateAge(dateOfBirth);
        }
        
        public System.Threading.Tasks.Task<int> CalculateAgeAsync(System.DateTime dateOfBirth) {
            return base.Channel.CalculateAgeAsync(dateOfBirth);
        }
    }
}
