//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost:8080/SelfService.ThousandDays", ConfigurationName="ICalculateThousandthDay")]
public interface ICalculateThousandthDay
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8080/SelfService.ThousandDays/ICalculateThousandthDay/CalculateT" +
        "housandthDayOfLife", ReplyAction="http://localhost:8080/SelfService.ThousandDays/ICalculateThousandthDay/CalculateT" +
        "housandthDayOfLifeResponse")]
    System.DateTime CalculateThousandthDayOfLife(System.DateTime dateOfBirth);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8080/SelfService.ThousandDays/ICalculateThousandthDay/CalculateT" +
        "housandthDayOfLife", ReplyAction="http://localhost:8080/SelfService.ThousandDays/ICalculateThousandthDay/CalculateT" +
        "housandthDayOfLifeResponse")]
    System.Threading.Tasks.Task<System.DateTime> CalculateThousandthDayOfLifeAsync(System.DateTime dateOfBirth);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ICalculateThousandthDayChannel : ICalculateThousandthDay, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CalculateThousandthDayClient : System.ServiceModel.ClientBase<ICalculateThousandthDay>, ICalculateThousandthDay
{
    
    public CalculateThousandthDayClient()
    {
    }
    
    public CalculateThousandthDayClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CalculateThousandthDayClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CalculateThousandthDayClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CalculateThousandthDayClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.DateTime CalculateThousandthDayOfLife(System.DateTime dateOfBirth)
    {
        return base.Channel.CalculateThousandthDayOfLife(dateOfBirth);
    }
    
    public System.Threading.Tasks.Task<System.DateTime> CalculateThousandthDayOfLifeAsync(System.DateTime dateOfBirth)
    {
        return base.Channel.CalculateThousandthDayOfLifeAsync(dateOfBirth);
    }
}
