//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.CalculateThousandthDay.Client.CalculateThousandthDayService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalculateThousandthDayService.CalculateThousandthDayServiceSoap")]
    public interface CalculateThousandthDayServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculateThousandthDayOfLife", ReplyAction="*")]
        System.DateTime CalculateThousandthDayOfLife(System.DateTime dateOfBirth);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculateThousandthDayOfLife", ReplyAction="*")]
        System.Threading.Tasks.Task<System.DateTime> CalculateThousandthDayOfLifeAsync(System.DateTime dateOfBirth);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculateThousandthDayServiceSoapChannel : WCF.CalculateThousandthDay.Client.CalculateThousandthDayService.CalculateThousandthDayServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculateThousandthDayServiceSoapClient : System.ServiceModel.ClientBase<WCF.CalculateThousandthDay.Client.CalculateThousandthDayService.CalculateThousandthDayServiceSoap>, WCF.CalculateThousandthDay.Client.CalculateThousandthDayService.CalculateThousandthDayServiceSoap {
        
        public CalculateThousandthDayServiceSoapClient() {
        }
        
        public CalculateThousandthDayServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculateThousandthDayServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculateThousandthDayServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculateThousandthDayServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.DateTime CalculateThousandthDayOfLife(System.DateTime dateOfBirth) {
            return base.Channel.CalculateThousandthDayOfLife(dateOfBirth);
        }
        
        public System.Threading.Tasks.Task<System.DateTime> CalculateThousandthDayOfLifeAsync(System.DateTime dateOfBirth) {
            return base.Channel.CalculateThousandthDayOfLifeAsync(dateOfBirth);
        }
    }
}
