//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.WorstMaleActorWinnerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WorstMaleActorWinnerService.WorstMaleActorWinnerSoap")]
    public interface WorstMaleActorWinnerSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetupWorstMaleActorWinners", ReplyAction="*")]
        void SetupWorstMaleActorWinners();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetupWorstMaleActorWinners", ReplyAction="*")]
        System.Threading.Tasks.Task SetupWorstMaleActorWinnersAsync();
        
        // CODEGEN: Generating message contract since element name year from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetActorByYear", ReplyAction="*")]
        Client.WorstMaleActorWinnerService.GetActorByYearResponse GetActorByYear(Client.WorstMaleActorWinnerService.GetActorByYearRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetActorByYear", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.WorstMaleActorWinnerService.GetActorByYearResponse> GetActorByYearAsync(Client.WorstMaleActorWinnerService.GetActorByYearRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetActorByYearRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetActorByYear", Namespace="http://tempuri.org/", Order=0)]
        public Client.WorstMaleActorWinnerService.GetActorByYearRequestBody Body;
        
        public GetActorByYearRequest() {
        }
        
        public GetActorByYearRequest(Client.WorstMaleActorWinnerService.GetActorByYearRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetActorByYearRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string year;
        
        public GetActorByYearRequestBody() {
        }
        
        public GetActorByYearRequestBody(string year) {
            this.year = year;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetActorByYearResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetActorByYearResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.WorstMaleActorWinnerService.GetActorByYearResponseBody Body;
        
        public GetActorByYearResponse() {
        }
        
        public GetActorByYearResponse(Client.WorstMaleActorWinnerService.GetActorByYearResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetActorByYearResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetActorByYearResult;
        
        public GetActorByYearResponseBody() {
        }
        
        public GetActorByYearResponseBody(string GetActorByYearResult) {
            this.GetActorByYearResult = GetActorByYearResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WorstMaleActorWinnerSoapChannel : Client.WorstMaleActorWinnerService.WorstMaleActorWinnerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WorstMaleActorWinnerSoapClient : System.ServiceModel.ClientBase<Client.WorstMaleActorWinnerService.WorstMaleActorWinnerSoap>, Client.WorstMaleActorWinnerService.WorstMaleActorWinnerSoap {
        
        public WorstMaleActorWinnerSoapClient() {
        }
        
        public WorstMaleActorWinnerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WorstMaleActorWinnerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorstMaleActorWinnerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorstMaleActorWinnerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SetupWorstMaleActorWinners() {
            base.Channel.SetupWorstMaleActorWinners();
        }
        
        public System.Threading.Tasks.Task SetupWorstMaleActorWinnersAsync() {
            return base.Channel.SetupWorstMaleActorWinnersAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.WorstMaleActorWinnerService.GetActorByYearResponse Client.WorstMaleActorWinnerService.WorstMaleActorWinnerSoap.GetActorByYear(Client.WorstMaleActorWinnerService.GetActorByYearRequest request) {
            return base.Channel.GetActorByYear(request);
        }
        
        public string GetActorByYear(string year) {
            Client.WorstMaleActorWinnerService.GetActorByYearRequest inValue = new Client.WorstMaleActorWinnerService.GetActorByYearRequest();
            inValue.Body = new Client.WorstMaleActorWinnerService.GetActorByYearRequestBody();
            inValue.Body.year = year;
            Client.WorstMaleActorWinnerService.GetActorByYearResponse retVal = ((Client.WorstMaleActorWinnerService.WorstMaleActorWinnerSoap)(this)).GetActorByYear(inValue);
            return retVal.Body.GetActorByYearResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.WorstMaleActorWinnerService.GetActorByYearResponse> Client.WorstMaleActorWinnerService.WorstMaleActorWinnerSoap.GetActorByYearAsync(Client.WorstMaleActorWinnerService.GetActorByYearRequest request) {
            return base.Channel.GetActorByYearAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.WorstMaleActorWinnerService.GetActorByYearResponse> GetActorByYearAsync(string year) {
            Client.WorstMaleActorWinnerService.GetActorByYearRequest inValue = new Client.WorstMaleActorWinnerService.GetActorByYearRequest();
            inValue.Body = new Client.WorstMaleActorWinnerService.GetActorByYearRequestBody();
            inValue.Body.year = year;
            return ((Client.WorstMaleActorWinnerService.WorstMaleActorWinnerSoap)(this)).GetActorByYearAsync(inValue);
        }
    }
}
