//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://SelfService.Hobby", ConfigurationName="ISearchForChampion")]
public interface ISearchForChampion
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://SelfService.Hobby/ISearchForChampion/GetChampionsByYear", ReplyAction="http://SelfService.Hobby/ISearchForChampion/GetChampionsByYearResponse")]
    string GetChampionsByYear(string year);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://SelfService.Hobby/ISearchForChampion/GetChampionsByYear", ReplyAction="http://SelfService.Hobby/ISearchForChampion/GetChampionsByYearResponse")]
    System.Threading.Tasks.Task<string> GetChampionsByYearAsync(string year);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ISearchForChampionChannel : ISearchForChampion, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class SearchForChampionClient : System.ServiceModel.ClientBase<ISearchForChampion>, ISearchForChampion
{
    
    public SearchForChampionClient()
    {
    }
    
    public SearchForChampionClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public SearchForChampionClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SearchForChampionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SearchForChampionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string GetChampionsByYear(string year)
    {
        return base.Channel.GetChampionsByYear(year);
    }
    
    public System.Threading.Tasks.Task<string> GetChampionsByYearAsync(string year)
    {
        return base.Channel.GetChampionsByYearAsync(year);
    }
}
