//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.BMI.Client.CalculateBMIService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalculateBMIService.CalculateBMIServiceSoap")]
    public interface CalculateBMIServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculateMyBMI", ReplyAction="*")]
        double CalculateMyBMI(double heightInMeters, double weight);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculateMyBMI", ReplyAction="*")]
        System.Threading.Tasks.Task<double> CalculateMyBMIAsync(double heightInMeters, double weight);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculateBMIServiceSoapChannel : WCF.BMI.Client.CalculateBMIService.CalculateBMIServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculateBMIServiceSoapClient : System.ServiceModel.ClientBase<WCF.BMI.Client.CalculateBMIService.CalculateBMIServiceSoap>, WCF.BMI.Client.CalculateBMIService.CalculateBMIServiceSoap {
        
        public CalculateBMIServiceSoapClient() {
        }
        
        public CalculateBMIServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculateBMIServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculateBMIServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculateBMIServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double CalculateMyBMI(double heightInMeters, double weight) {
            return base.Channel.CalculateMyBMI(heightInMeters, weight);
        }
        
        public System.Threading.Tasks.Task<double> CalculateMyBMIAsync(double heightInMeters, double weight) {
            return base.Channel.CalculateMyBMIAsync(heightInMeters, weight);
        }
    }
}
