//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://SelfService.BMI", ConfigurationName="IBMICalculator")]
public interface IBMICalculator
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://SelfService.BMI/IBMICalculator/CalculateMyBMI", ReplyAction="http://SelfService.BMI/IBMICalculator/CalculateMyBMIResponse")]
    double CalculateMyBMI(double heightInMeters, double weight);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://SelfService.BMI/IBMICalculator/CalculateMyBMI", ReplyAction="http://SelfService.BMI/IBMICalculator/CalculateMyBMIResponse")]
    System.Threading.Tasks.Task<double> CalculateMyBMIAsync(double heightInMeters, double weight);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IBMICalculatorChannel : IBMICalculator, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class BMICalculatorClient : System.ServiceModel.ClientBase<IBMICalculator>, IBMICalculator
{
    
    public BMICalculatorClient()
    {
    }
    
    public BMICalculatorClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public BMICalculatorClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BMICalculatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BMICalculatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public double CalculateMyBMI(double heightInMeters, double weight)
    {
        return base.Channel.CalculateMyBMI(heightInMeters, weight);
    }
    
    public System.Threading.Tasks.Task<double> CalculateMyBMIAsync(double heightInMeters, double weight)
    {
        return base.Channel.CalculateMyBMIAsync(heightInMeters, weight);
    }
}
