//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.GetNamesDayDateService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GetNamesDayDateService.GetNamesDayDateServiceSoap")]
    public interface GetNamesDayDateServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetupNamesDayDictionary", ReplyAction="*")]
        void SetupNamesDayDictionary();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetupNamesDayDictionary", ReplyAction="*")]
        System.Threading.Tasks.Task SetupNamesDayDictionaryAsync();
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNamesDayDateByName", ReplyAction="*")]
        Client.GetNamesDayDateService.GetNamesDayDateByNameResponse GetNamesDayDateByName(Client.GetNamesDayDateService.GetNamesDayDateByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNamesDayDateByName", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.GetNamesDayDateService.GetNamesDayDateByNameResponse> GetNamesDayDateByNameAsync(Client.GetNamesDayDateService.GetNamesDayDateByNameRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNamesDayDateByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNamesDayDateByName", Namespace="http://tempuri.org/", Order=0)]
        public Client.GetNamesDayDateService.GetNamesDayDateByNameRequestBody Body;
        
        public GetNamesDayDateByNameRequest() {
        }
        
        public GetNamesDayDateByNameRequest(Client.GetNamesDayDateService.GetNamesDayDateByNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNamesDayDateByNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public GetNamesDayDateByNameRequestBody() {
        }
        
        public GetNamesDayDateByNameRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNamesDayDateByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNamesDayDateByNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.GetNamesDayDateService.GetNamesDayDateByNameResponseBody Body;
        
        public GetNamesDayDateByNameResponse() {
        }
        
        public GetNamesDayDateByNameResponse(Client.GetNamesDayDateService.GetNamesDayDateByNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNamesDayDateByNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetNamesDayDateByNameResult;
        
        public GetNamesDayDateByNameResponseBody() {
        }
        
        public GetNamesDayDateByNameResponseBody(string GetNamesDayDateByNameResult) {
            this.GetNamesDayDateByNameResult = GetNamesDayDateByNameResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetNamesDayDateServiceSoapChannel : Client.GetNamesDayDateService.GetNamesDayDateServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetNamesDayDateServiceSoapClient : System.ServiceModel.ClientBase<Client.GetNamesDayDateService.GetNamesDayDateServiceSoap>, Client.GetNamesDayDateService.GetNamesDayDateServiceSoap {
        
        public GetNamesDayDateServiceSoapClient() {
        }
        
        public GetNamesDayDateServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetNamesDayDateServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetNamesDayDateServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetNamesDayDateServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SetupNamesDayDictionary() {
            base.Channel.SetupNamesDayDictionary();
        }
        
        public System.Threading.Tasks.Task SetupNamesDayDictionaryAsync() {
            return base.Channel.SetupNamesDayDictionaryAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.GetNamesDayDateService.GetNamesDayDateByNameResponse Client.GetNamesDayDateService.GetNamesDayDateServiceSoap.GetNamesDayDateByName(Client.GetNamesDayDateService.GetNamesDayDateByNameRequest request) {
            return base.Channel.GetNamesDayDateByName(request);
        }
        
        public string GetNamesDayDateByName(string name) {
            Client.GetNamesDayDateService.GetNamesDayDateByNameRequest inValue = new Client.GetNamesDayDateService.GetNamesDayDateByNameRequest();
            inValue.Body = new Client.GetNamesDayDateService.GetNamesDayDateByNameRequestBody();
            inValue.Body.name = name;
            Client.GetNamesDayDateService.GetNamesDayDateByNameResponse retVal = ((Client.GetNamesDayDateService.GetNamesDayDateServiceSoap)(this)).GetNamesDayDateByName(inValue);
            return retVal.Body.GetNamesDayDateByNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.GetNamesDayDateService.GetNamesDayDateByNameResponse> Client.GetNamesDayDateService.GetNamesDayDateServiceSoap.GetNamesDayDateByNameAsync(Client.GetNamesDayDateService.GetNamesDayDateByNameRequest request) {
            return base.Channel.GetNamesDayDateByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.GetNamesDayDateService.GetNamesDayDateByNameResponse> GetNamesDayDateByNameAsync(string name) {
            Client.GetNamesDayDateService.GetNamesDayDateByNameRequest inValue = new Client.GetNamesDayDateService.GetNamesDayDateByNameRequest();
            inValue.Body = new Client.GetNamesDayDateService.GetNamesDayDateByNameRequestBody();
            inValue.Body.name = name;
            return ((Client.GetNamesDayDateService.GetNamesDayDateServiceSoap)(this)).GetNamesDayDateByNameAsync(inValue);
        }
    }
}
