//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost:8080/SelfService.CalculateAge", ConfigurationName="ICalculateAge")]
public interface ICalculateAge
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8080/SelfService.CalculateAge/ICalculateAge/CalculateAge", ReplyAction="http://localhost:8080/SelfService.CalculateAge/ICalculateAge/CalculateAgeResponse" +
        "")]
    int CalculateAge(System.DateTime dateOfBirth);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8080/SelfService.CalculateAge/ICalculateAge/CalculateAge", ReplyAction="http://localhost:8080/SelfService.CalculateAge/ICalculateAge/CalculateAgeResponse" +
        "")]
    System.Threading.Tasks.Task<int> CalculateAgeAsync(System.DateTime dateOfBirth);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ICalculateAgeChannel : ICalculateAge, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CalculateAgeClient : System.ServiceModel.ClientBase<ICalculateAge>, ICalculateAge
{
    
    public CalculateAgeClient()
    {
    }
    
    public CalculateAgeClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CalculateAgeClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CalculateAgeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CalculateAgeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int CalculateAge(System.DateTime dateOfBirth)
    {
        return base.Channel.CalculateAge(dateOfBirth);
    }
    
    public System.Threading.Tasks.Task<int> CalculateAgeAsync(System.DateTime dateOfBirth)
    {
        return base.Channel.CalculateAgeAsync(dateOfBirth);
    }
}
